name: GCP Security Scan

on:
  pull_request:
    branches: [main]
    paths:
      - "pose-est-infra/gcp/**"

jobs:
  checkov:
    name: Checkov Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6cd4363f9995 # v12.1347.0
        with:
          directory: pose-est-infra/gcp/terraform
          framework: terraform
          output_format: cli,sarif
          output_file_path: console,results.sarif
          soft_fail: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@45c373516f557556c15d420e3f5e0aa3d64366bc # v3.31.9
        with:
          sarif_file: results.sarif
          category: checkov-gcp
